// <auto-generated />
using System;
using KS_Payroll.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KS_Payroll.Migrations
{
    [DbContext(typeof(KS_PayrollContext))]
    [Migration("20230113205559_loadhj")]
    partial class loadhj
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.AdvanceLoan", b =>
                {
                    b.Property<int>("ALid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpIDCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("empid")
                        .HasColumnType("int");

                    b.HasKey("ALid");

                    b.ToTable("AdvanceLoan");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.AttendanceModule", b =>
                {
                    b.Property<int>("AMid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AModuleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time2Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AMid");

                    b.ToTable("AttendanceModule");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Calendar", b =>
                {
                    b.Property<int>("CalendarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("Days")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Eventstats")
                        .HasColumnType("int");

                    b.Property<string>("Eventtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<string>("OccassionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CalendarID");

                    b.ToTable("Calendar");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Comapny", b =>
                {
                    b.Property<int>("Cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Cid");

                    b.ToTable("Comapny");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Designation", b =>
                {
                    b.Property<int>("DesigID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AttenBonus")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("DesigName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<double>("HolidayAllowance")
                        .HasColumnType("float");

                    b.Property<double>("IftarBill")
                        .HasColumnType("float");

                    b.Property<double>("LunchBill")
                        .HasColumnType("float");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<double>("NightBill")
                        .HasColumnType("float");

                    b.Property<bool>("OverTime")
                        .HasColumnType("bit");

                    b.Property<double>("TiffinBill")
                        .HasColumnType("float");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DesigID");

                    b.ToTable("Designation");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.DesignationType", b =>
                {
                    b.Property<int>("DesignationTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("DesignationTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DesignationTypeId");

                    b.ToTable("DesignationType");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Employeeinfo", b =>
                {
                    b.Property<int>("empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<int>("EmpAttenBonus")
                        .HasColumnType("int");

                    b.Property<string>("EmpBODCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpBankAcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpBankBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpBankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpBasic")
                        .HasColumnType("int");

                    b.Property<string>("EmpBlood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EmpBodImg")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EmpChildNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpCompany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EmpContractImg")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("EmpConveyance")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmpDOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpDesignationTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpDesignationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpEduPassG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpEduPassY")
                        .HasColumnType("int");

                    b.Property<string>("EmpEduStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpEduTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpEmgPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpEmgphone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpFName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpFloor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpFood")
                        .HasColumnType("int");

                    b.Property<string>("EmpGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpGrade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpGross")
                        .HasColumnType("int");

                    b.Property<int>("EmpHeight")
                        .HasColumnType("int");

                    b.Property<int>("EmpHolidayAlw")
                        .HasColumnType("int");

                    b.Property<int>("EmpHouse")
                        .HasColumnType("int");

                    b.Property<string>("EmpIDCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpIftarBill")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmpJoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpLunchBilll")
                        .HasColumnType("int");

                    b.Property<string>("EmpMFSName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpMName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpMarriedStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpMedical")
                        .HasColumnType("int");

                    b.Property<string>("EmpNID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EmpNIDImg")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EmpName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpNationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpNightBill")
                        .HasColumnType("int");

                    b.Property<string>("EmpNomineeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpNomineePhn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpNomineeRlt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmpOverTime")
                        .HasColumnType("bit");

                    b.Property<string>("EmpParmanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpParmanentArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpParmanentDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpParmanentZip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpPassport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EmpPassportImg")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EmpPayMethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpPresentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpPresentArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpPresentDistrict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpPresentZip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EmpPrfImg")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EmpRefName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpRefNumber")
                        .HasColumnType("int");

                    b.Property<string>("EmpReligion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpSecrateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpSection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpShift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("EmpSigImg")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EmpSpouseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpStats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpTiffinBill")
                        .HasColumnType("int");

                    b.Property<string>("EmpType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpWeight")
                        .HasColumnType("int");

                    b.Property<string>("MFSnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("empid");

                    b.ToTable("Employeeinfo");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.FinalAttendance", b =>
                {
                    b.Property<int>("sl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttenStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EarlyOut")
                        .HasColumnType("time");

                    b.Property<string>("EmpSCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Late")
                        .HasColumnType("time");

                    b.Property<string>("OutTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OverTime")
                        .HasColumnType("int");

                    b.Property<int>("empid")
                        .HasColumnType("int");

                    b.HasKey("sl");

                    b.ToTable("FinalAttendance");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Floor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("FloorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FloorId");

                    b.ToTable("Floor");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("GradeTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Leave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("LeaveTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfDays")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LeaveId");

                    b.ToTable("Leave");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Leaveinfo", b =>
                {
                    b.Property<int>("LID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ComID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("EmpCardID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leave_Bonus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leave_Days")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Leave_End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Leave_Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Leave_Stats")
                        .HasColumnType("int");

                    b.Property<string>("Leave_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Leave_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LID");

                    b.ToTable("Leaveinfo");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Line", b =>
                {
                    b.Property<int>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<string>("LineTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LineId");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Loan", b =>
                {
                    b.Property<int>("ALid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmpIDCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<float>("TimePerioad")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("empid")
                        .HasColumnType("int");

                    b.HasKey("ALid");

                    b.ToTable("Loan");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.RowAttendance", b =>
                {
                    b.Property<int>("SL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Frist_In_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Last_Out_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("empSCode")
                        .HasColumnType("float");

                    b.HasKey("SL");

                    b.ToTable("RowAttendance");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SectionId");

                    b.ToTable("Section");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BreakEndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreakStartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("EndTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<string>("ShiftTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ShiftId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.TempJobCard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EarlyOut")
                        .HasColumnType("time");

                    b.Property<string>("InTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("LateTime")
                        .HasColumnType("time");

                    b.Property<string>("OutTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OverTime")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TempJobCard");
                });

            modelBuilder.Entity("KS_Payroll.Areas.Admin.Data.Uunemployees", b =>
                {
                    b.Property<int>("sl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AsingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Created_By")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpIDCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoningDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastAttendance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeftType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedId")
                        .HasColumnType("int");

                    b.Property<string>("Short_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Updated_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Updated_By")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("empid")
                        .HasColumnType("int");

                    b.HasKey("sl");

                    b.ToTable("Uunemployees");
                });
#pragma warning restore 612, 618
        }
    }
}
